FROM node:20 AS build
WORKDIR /app
COPY ./package*.json ./
COPY ./vite.config.js ./
COPY ./index.html ./
COPY ./src/js ./src
RUN npm install && npm run build

FROM nginx:stable-alpine
COPY ./nginx/* /etc/nginx/templates/
COPY --from=build /app/dist /usr/share/nginx/html
EXPOSE 80