services:

  frontend:
    image: projet_initiative_asso-frontend
    build:
      context: .
      dockerfile: Dockerfile-frontend
    depends_on:
      - backend
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.morgan-web.rule=Host(`morgan.nocturlab.fr`)"
      - "traefik.http.services.morgan-web.loadbalancer.server.port=80"
    networks:
      - traefik
      - app
    environment:
      API_URL: http://backend:8080

  backend:
    image: projet_initiative_asso-backend
    build:
      context: .
      dockerfile: Dockerfile-backend
    ports:
      - "8075:8080"
    environment:
        DB_HOST: db
        DB_PORT: 5432
        DB_NAME: db_initiative_asso
        DB_USERNAME: postgres
        DB_PASSWORD: postgres
    depends_on:
      - db
    networks:
      - db
      - app

  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: db_initiative_asso
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - db

networks:
  db:
  traefik:
    external: true
    name: traefik_default
  app:
    driver: bridge

volumes:
  postgres-data: