FROM node:20 AS build
WORKDIR /app
COPY ./package*.json ./
COPY ./vite.config.js ./
COPY ./index.html ./
COPY ./src/js ./src/js
RUN npm install && npm run build

FROM nginx:stable-alpine
COPY ./nginx/* /etc/nginx/conf.d/default.conf
COPY --from=build /app/dist /usr/share/nginx/html
EXPOSE 80

#COPY --from=build /app/dist /usr/share/nginx/html
#EXPOSE 80
#CMD ["nginx", "-g", "daemon off;"]
