spring:
  application:
    name: initiative-asso

  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:db_initiative_asso}
    username: postgres
    password: postgres

  flyway:
    locations: classpath:db/migration
    enabled: true
    baseline-on-migrate: true
    validate-on-migrate: true

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update

  security:
    user:
      name: user
      password: password

jwt:
  secret: "jW91clNlY3JldEtleUhhc2hCYXNlNjRTbG9uZ1BhZGRpbmc="
  expiration:  3600000 #Durée en millisecondes

server:
  servlet:
    context-path: /api

logging:
  level:
    org:
      flyway: DEBUG
      springframework:
        security: DEBUG
        web.socket: DEBUG
        messaging: DEBUG

#      springframework: DEBUG