spring:
  application:
    name: initiative-asso

  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/db_initiative_asso
    username: postgres
    password: postgres

  flyway:
    locations: classpath:db/migration
    enabled: true
    baseline-on-migrate: true
    validate-on-migrate: true

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update

  security:
    user:
      name: user
      password: password

# généré sur encryption key generator de RandomGenerate.io
jwt:
  secret: "a786d7b256d30a6cd6cd560123197e2cc18bf09218ef78423c4aab9a049a1573"
  expiration:  3600000 #Durée en millisecondes

server:
  servlet:
    context-path: /api

logging:
  level:
    org:
      flyway: DEBUG
      springframework.security: DEBUG
#      springframework: DEBUG