spring:
  application:
    name: initiative-asso

  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/db_initiative_asso
    username: postgres
    password: postgres

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update

  security:
    user:
      name: user
      password: password

server:
  servlet:
    context-path: /api

logging:
  level:
    org.springframework.security:
      DEBUG

springdoc:
  api-docs:
    path: /api-docs

