spring:
  application:
    name: initiative-asso

  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/db_initiative_asso
    username: postgres
    password: postgres

  jpa:
    show-sql: true
    database: postgresql
    hibernate:
      ddl-auto: update

  security:
    user:
      name: user
      password: password
