package fr.morgan.initiativeasso.model.enums;

public enum DomainesActivite {
    SERVICES_ADMINISTRATIFS_ET_SOUTIEN,
    ACTIVITES_SPECIALISEES_SCIENTIFIQUES_ET_TECHNIQUES,
    AGRICULTURE_SYLVICULTURE_PECHE,
    ARTS_SPECTACLES_ET_ACTIVITES_RECREATIVES,
    COMMERCE_ET_REPARATION,
    CONSTRUCTION_BTP,
    ENSEIGNEMENT,
    HOTELS_CAFES_ET_RESTAURANTS,
    INDUSTRIE,
    INFORMATION_ET_COMMUNICATION,
    PRODUCTION_ET_DISTRIBUTION_EAU_ASSAINISSEMENT_GESTION_DECHETS_DEPOLLUTION,
    PRODUCTION_ET_DISTRIBUTION_ELECTRICITE_GAZ_VAPEUR_AIR_CONDITIONNE,
    SANTE_HUMAINE_ET_ACTION_SOCIALE,
    SERVICES_AUX_ENTREPRISES,
    SERVICES_AUX_PARTICULIERS,
    TRANSPORTS
}
