create table adresse
(
    code_postal    integer      not null,
    id             bigint generated by default as identity
        primary key,
    complement     varchar(255),
    numero_de_voie varchar(255),
    rue            varchar(255),
    ville          varchar(255) not null
);

alter table adresse
    owner to postgres;

create table "user"
(
    first_login        boolean      not null,
    is_account_enabled boolean      not null,
    id                 bigint generated by default as identity
        primary key,
    email              varchar(255) not null
        unique,
    entreprise         varchar(255) not null,
    nom                varchar(255) not null,
    password           varchar(255) not null,
    plate_forme        varchar(255) not null
        constraint user_plate_forme_check
            check ((plate_forme)::text = ANY
                   (ARRAY [('DEUXSEVRES'::character varying)::text, ('CHARENTEMARITIME'::character varying)::text, ('CHARENTE'::character varying)::text, ('GIRONDE'::character varying)::text])),
    prenom             varchar(255) not null
);

alter table "user"
    owner to postgres;

create table message
(
    read        boolean not null,
    id          bigint generated by default as identity
        primary key,
    receiver_id bigint
        constraint fk41up0jg8hwcloimjuh278yck8
            references "user",
    sender_id   bigint
        constraint fk49xxdqy6p6kxedwvpjyuvnkf
            references "user",
    time_stamp  timestamp(6),
    text        varchar(2000)
);

alter table message
    owner to postgres;

create table notification
(
    date_notification timestamp(6) not null,
    id                bigint generated by default as identity
        primary key,
    receiver_id       bigint       not null
        constraint fks951ba5cqr6ibbu6w295b3ljg
            references "user",
    sender_id         bigint       not null
        constraint fks5bgylrbvexk23n1gucpsbtat
            references "user"
);

alter table notification
    owner to postgres;

create table parrain
(
    domaine_activite     smallint
        constraint parrain_domaine_activite_check
            check ((domaine_activite >= 0) AND (domaine_activite <= 15)),
    id                   bigint not null
        primary key
        constraint fke45qejcxunc7p58ucwoxp5u6i
            references "user",
    disponibilites       varchar(255),
    parcours             varchar(255),
    zones_de_deplacement smallint[]
);

alter table parrain
    owner to postgres;

create table porteur
(
    date_debut_activite date,
    domaine_activite    smallint
        constraint porteur_domaine_activite_check
            check ((domaine_activite >= 0) AND (domaine_activite <= 15)),
    id                  bigint not null
        primary key
        constraint fkv0wbt7rroph39crvisbt9jhh
            references "user",
    lieu_activite_id    bigint
        constraint fkk8c3yg1i7n5q566cksoq4mh26
            references adresse,
    parrain_id          bigint
        constraint fkrrttq6sdhb94rf4gvi2j027ep
            references parrain,
    descriptif_activite varchar(255),
    disponibilites      varchar(255),
    besoins_potentiels  smallint[]
);

alter table porteur
    owner to postgres;

create table salarie_asso
(
    id       bigint not null
        primary key
        constraint fkaug253e7tlpxixiyu9g1atsa2
            references "user",
    fonction varchar(255)
);

alter table salarie_asso
    owner to postgres;

create table user_roles
(
    user_id bigint       not null
        constraint fk7ivp84f52aa3vd7ndq0oh0279
            references "user",
    roles   varchar(255) not null
        constraint user_roles_roles_check
            check ((roles)::text = ANY
                   (ARRAY [('ADMIN'::character varying)::text, ('ASSO'::character varying)::text, ('PORTEUR'::character varying)::text, ('PARRAIN'::character varying)::text]))
);

alter table user_roles
    owner to postgres;

create table reunion
(
    id           bigint generated by default as identity
        primary key,
    compte_rendu varchar(255),
    date         timestamp(6),
    motif        varchar(255),
    parrain_id   bigint
        constraint fkggs16hdrl564adpp7afw6xjhc
            references parrain,
    porteur_id   bigint
        constraint fk5e6csaw6xgtcoeadf29ppxv5n
            references porteur
);

alter table reunion
    owner to postgres;
