create table adresse
(
    code_postal    integer      not null,
    id             bigint generated by default as identity
        primary key,
    complement     varchar(255),
    numero_de_voie varchar(255),
    rue            varchar(255),
    ville          varchar(255) not null
);

alter table adresse
    owner to postgres;

create table type_accompagnement
(
    id      bigint generated by default as identity
        primary key,
    libelle varchar(255) not null
        unique
);

alter table type_accompagnement
    owner to postgres;

create table "user"
(
    first_login        boolean      not null,
    is_account_enabled boolean      not null,
    adresse_id         bigint
        constraint fkdl2g99c51ey5qyqy18159vav
            references adresse,
    id                 bigint generated by default as identity
        primary key,
    email              varchar(255) not null
        unique,
    entreprise         varchar(255) not null,
    nom                varchar(255) not null,
    password           varchar(255) not null,
    plate_forme        varchar(255) not null
        constraint user_plate_forme_check
            check ((plate_forme)::text = ANY
                   ((ARRAY ['DEUXSEVRES'::character varying, 'CHARENTEMARITIME'::character varying, 'CHARENTE'::character varying, 'GIRONDE'::character varying])::text[])),
    prenom             varchar(255) not null
);

alter table "user"
    owner to postgres;

create table parrain
(
    domaine_activite     smallint
        constraint parrain_domaine_activite_check
            check ((domaine_activite >= 0) AND (domaine_activite <= 15)),
    id                   bigint not null
        primary key
        constraint fke45qejcxunc7p58ucwoxp5u6i
            references "user",
    disponibilites       varchar(255),
    parcours             varchar(255),
    zones_de_deplacement smallint[]
);

alter table parrain
    owner to postgres;

create table porteur
(
    date_debut_activite date,
    domaine_activite    smallint
        constraint porteur_domaine_activite_check
            check ((domaine_activite >= 0) AND (domaine_activite <= 15)),
    id                  bigint not null
        primary key
        constraint fkv0wbt7rroph39crvisbt9jhh
            references "user",
    lieu_activite_id    bigint
        constraint fkk8c3yg1i7n5q566cksoq4mh26
            references adresse,
    descriptif_activite varchar(255),
    disponibilites      varchar(255)
);

alter table porteur
    owner to postgres;

create table porteur_typeaccompagnement
(
    porteur_id             bigint not null
        constraint fkeh9fxn787ewoj1j8yg084ejyy
            references porteur,
    type_accompagnement_id bigint not null
        constraint fkg2655t2ctdp07is0qhiokkxp5
            references type_accompagnement
);

alter table porteur_typeaccompagnement
    owner to postgres;

create table salarie_asso
(
    id       bigint not null
        primary key
        constraint fkaug253e7tlpxixiyu9g1atsa2
            references "user",
    fonction varchar(255)
);

alter table salarie_asso
    owner to postgres;

create table user_roles
(
    user_id bigint       not null
        constraint fk7ivp84f52aa3vd7ndq0oh0279
            references "user",
    roles   varchar(255) not null
        constraint user_roles_roles_check
            check ((roles)::text = ANY
                   ((ARRAY ['ADMIN'::character varying, 'ASSO'::character varying, 'PORTEUR'::character varying, 'PARRAIN'::character varying])::text[]))
);

alter table user_roles
    owner to postgres;

