create table likes
(
    date_creation timestamp(6) not null,
    id            bigint generated by default as identity
        primary key,
    liked_user_id bigint       not null
        constraint fk4vqqpuf6wdt7rwrn0g6jpi0sj
            references "user",
    user_id       bigint       not null
        constraint fkgnujyqu0fqtv970byhekkrsiv
            references "user"
);

alter table likes
    owner to postgres;
