name: Deploy on server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup SSH key
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.DEPLOY_SSH_SECRET }}

      - name: Test SSH connection
        run: ssh -o StrictHostKeyChecking=no mbleunven@ssh.shiipou.fr "echo 'Connexion SSH OK'"

      - name: Deploy to server via SSH
        run: |
          ssh -o StrictHostKeyChecking=no mbleunven@ssh.shiipou.fr << 'EOF'
            cd /var/home/mbleunven/fil_rouge
            git pull origin main
            docker compose pull
            docker compose up -d --build
          EOF